"""empty message

Revision ID: bc820a811d79
Revises: 7ef415f9b01a
Create Date: 2024-10-17 09:31:18.126186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc820a811d79'
down_revision = '7ef415f9b01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.alter_column('hero_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('power_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hero_powers', schema=None) as batch_op:
        batch_op.alter_column('power_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('hero_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
